title: Bootspec TDD
markdown: rdiscount
root: /discover/
pygments: true

author:
  name: Jonathan Lozinksi
  email: jonathan.lozinski@gmail.com
  github: loz
  twitter: jlozinski

JB:
  ASSET_PATH: /discover/assets/themes/twitter
